"""initial models

Revision ID: 5af601905391
Revises: 
Create Date: 2026-05-11 17:28:32.079364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5af601905391'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist')
    op.drop_table('library_items')
    with op.batch_alter_table('episode_reviews', schema=None) as batch_op:
        batch_op.drop_constraint('uq_episode_review_user_episode', type_='unique')
        batch_op.create_unique_constraint('uq_user_episode_review', ['user_id', 'series_id', 'season_number', 'episode_number'])
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('vote_average', sa.Float(), nullable=True))
        batch_op.drop_constraint('uq_favourite_user_tmdb', type_='unique')
        batch_op.create_unique_constraint('uq_user_favourite_tmdb', ['user_id', 'tmdb_id'])
        batch_op.drop_column('title')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_constraint('uq_user_favourite_tmdb', type_='unique')
        batch_op.create_unique_constraint('uq_favourite_user_tmdb', ['user_id', 'tmdb_id'])
        batch_op.drop_column('vote_average')
        batch_op.drop_column('name')

    with op.batch_alter_table('episode_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.drop_constraint('uq_user_episode_review', type_='unique')
        batch_op.create_unique_constraint('uq_episode_review_user_episode', ['user_id', 'series_id', 'season_number', 'episode_number'])

    op.create_table('library_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('tmdb_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('poster_path', sa.VARCHAR(length=300), nullable=True),
    sa.Column('platform', sa.VARCHAR(length=120), nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=True),
    sa.Column('progress_percent', sa.INTEGER(), nullable=False),
    sa.Column('added_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tmdb_id', name='uq_library_user_tmdb')
    )
    op.create_table('watchlist',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('tmdb_id', sa.INTEGER(), nullable=False),
    sa.Column('added_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tmdb_id', name='uq_user_tmdb')
    )
    # ### end Alembic commands ###
